MvcDbStock/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcDbStock.Models.Entity;

namespace MvcDbStock.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        MvcDbStockEntities db = new MvcDbStockEntities();
        public ActionResult Index()
        {
            var değerler = db.TblUrunler.ToList();
            return View(değerler);
        }
        [HttpGet]
        public ActionResult YeniÜrünEkle()
        {
            List<SelectListItem> degerler = (from i in db.TblKategori.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORİAD,
                                                 Value = i.KATEGORID.ToString()
                                             }).ToList();
            ViewBag.item = degerler;
            return View();
        }
        [HttpPost]
        public ActionResult YeniÜrünEkle(TblUrunler tblUrunler)
        {
            var ktg = db.TblKategori.Where(x => x.KATEGORID == tblUrunler.TblKategori.KATEGORID).FirstOrDefault();
            tblUrunler.TblKategori = ktg;
            db.TblUrunler.Add(tblUrunler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunSil(int id)
        {
            var degerler = db.TblUrunler.Find(id);
            db.TblUrunler.Remove(degerler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunGüncelle(int id)
        {
            var urun = db.TblUrunler.Find(id);

            List<SelectListItem> degerler = (from i in db.TblKategori.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORİAD,
                                                 Value = i.KATEGORID.ToString()
                                             }).ToList();
            ViewBag.item = degerler;
            return View("UrunGüncelle", urun);

        }
        public ActionResult UrunGetir(TblUrunler tblUrunler)
        {
            var result = db.TblUrunler.Find(tblUrunler.URUNID);
            result.URUNAD = tblUrunler.URUNAD;
            result.MARKA = tblUrunler.MARKA;
            result.STOK = tblUrunler.STOK;
            result.FIYAT = tblUrunler.FIYAT;
            result.URUNKATEGORI = tblUrunler.URUNKATEGORI;
            var ktg = db.TblKategori.Where(x => x.KATEGORID == tblUrunler.TblKategori.KATEGORID).FirstOrDefault();
            result.URUNKATEGORI = ktg.KATEGORID;
            db.SaveChanges();
            return RedirectToAction("Index");

            //return View("UrunGüncelle", urun);

        }

    }
}

MvcDbStock/Views/Urun/Index.cshtml
@using MvcDbStock.Models.Entity;
@model List<TblUrunler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<h2>Ürünler Listeleme Sayfası</h2>

<table id="tbl1 " class="table table-bordered">
    <thead>
        <tr>
            <th>Ürün ID</th>
            <th>ÜRÜN AD</th>
            <th>MARKA</th>
            <th>Kategori</th>
            <th>FİYAT</th>
            <th>STOK</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.URUNID</td>
                <td>@item.URUNAD</td>
                <td>@item.MARKA</td>
                <td>@item.TblKategori.KATEGORİAD</td>
                <td>@item.FIYAT</td>
                <td>@item.STOK</td>
                <td><a href="/Urun/UrunSil/@item.URUNID" class=" btn btn-danger">Sil</a></td>
                <td><a href="/Urun/UrunGüncelle/@item.URUNID" class=" btn btn-success">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/Urun/YeniÜrünEkle/" class="btn btn-info">Yeni Ürün</a>


<link href="~/Content/DataTables/css/buttons.bootstrap4.css" rel="stylesheet" />
<script type="text/javascript" src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

<script>
    $('#tbl1').DataTable();
</script>

MvcDbStock/Views/Urun/UrunGüncelle.cshtml
@model MvcDbStock.Models.Entity.TblUrunler
@{
    ViewBag.Title = "UrunGüncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("UrunGetir", "Urun", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(x => x.URUNID)
    @Html.TextBoxFor(x => x.URUNID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.URUNAD)
    @Html.TextBoxFor(x => x.URUNAD, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.URUNKATEGORI)
    @Html.DropDownListFor(x=>x.TblKategori.KATEGORID,(List<SelectListItem>)ViewBag.item, new { @class = "form-control" })
    @*@Html.TextBoxFor(x => x.URUNKATEGORI, new { @class = "form-control" })*@
    <br />
    @Html.LabelFor(x => x.MARKA)
    @Html.TextBoxFor(x => x.MARKA, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FIYAT)
    @Html.TextBoxFor(x => x.FIYAT, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.STOK)
    @Html.TextBoxFor(x => x.STOK, new { @class = "form-control" })
    <br />

    <button class="btn btn-primary">Ürün  Güncelle</button>


</div>
}

MvcDbStock/Views/Urun/YeniÜrünEkle.cshtml
@model MvcDbStock.Models.Entity.TblUrunler
@{
    ViewBag.Title = "YeniÜrünEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Yeni Ürün Ekleme Sayfası</h2>

<form method="post">
    <div>
        <label>Ürün Adı</label>
        <input type="text" class="form-control" name="URUNAD" required="" maxlength="30" placeholder="Ürün Adını Giriniz" />
    </div>
    <div>
        <label>Marka</label>
        <input type="text" class="form-control" name="MARKA" required="" />
    </div>
    <div>

        <label>Ürün Kategori</label>
        @Html.DropDownListFor(x => x.TblKategori.KATEGORID, (List<SelectListItem>)ViewBag.item, new { @class = "form-control" })

    </div>
    <div>
        <label>Fiyat</label>
        <input type="text" class="form-control" name="FIYAT" required="" />
    </div>
    <div>
        <label>Stok</label>

        <input type="text" class="form-control" name="STOK" required="" />


        <br />
        <button class="btn btn-info">Kayıt Ekle</button>
    </div>

</form>