MvcDbStock/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcDbStock.Models.Entity;

namespace MvcDbStock.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        MvcDbStockEntities db = new MvcDbStockEntities();
        public ActionResult Index(string p)
        {
            var degerler = from d in db.TblMüsteri select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(x => x.MÜSTERIAD.Contains(p));
            }
            return View(degerler.ToList());
        }
        [HttpGet]
        public ActionResult YeniMüsteriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMüsteriEkle(TblMüsteri tblMüsteri)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMüsteriEkle");
            }
            db.TblMüsteri.Add(tblMüsteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MüsteriSil(int id)
        {
            var müsteri = db.TblMüsteri.Find(id);
            db.TblMüsteri.Remove(müsteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MüsteriGetir(int id)
        {
            var mus = db.TblMüsteri.Find(id);
            return View("MüsteriGetir", mus);
        }
        public ActionResult Guncelle(TblMüsteri tblMüsteri)
        {
            var mus = db.TblMüsteri.Find(tblMüsteri.MUSTERIID);
            mus.MÜSTERIAD = tblMüsteri.MÜSTERIAD;
            mus.MUSTERISOYAD = tblMüsteri.MUSTERISOYAD;

            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

MvcDbStock/Views/Musteri/Index.cshtml
@using MvcDbStock.Models.Entity;
@model List<TblMüsteri>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Müşteri Listeleme Sayfası</h2>


@using (Html.BeginForm("Index", "Musteri", FormMethod.Get))
{
    <p>
        <b> Aranacak Müşteri:</b>@Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>
}
<table class="table table-bordered">

    <tr>
        <th>Müşteri ID</th>
        <th>Müşteri AD</th>
        <th>Müşteri Soyad</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Alert</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.MUSTERIID</th>
            <td>@item.MÜSTERIAD</td>
            <td>@item.MUSTERISOYAD</td>
            <td><a href="/Musteri/MüsteriSil/@item.MUSTERIID" class=" btn btn-danger">Sil</a></td>
            <td><a href="/Musteri/MüsteriGetir/@item.MUSTERIID" class=" btn btn-success">Güncelle</a></td>
         

            <td>@Html.ActionLink("SİL BUTONU", "MüsteriSil", new { id = item.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('Gerçekten Silmek İstiyormusunuz?')" })</td>

           
        </tr>
    }
</table>
<a href="/Musteri/YeniMüsteriEkle/" class="btn btn-info">Yeni Müşteri Ekle</a>

MvcDbStock/Views/Musteri/MüsteriGetir.cshtml
@model MvcDbStock.Models.Entity.TblMüsteri
@{
    ViewBag.Title = "MüsteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Müsteri Getir</h2>

@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.MUSTERIID)
        @Html.TextBoxFor(x => x.MUSTERIID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.MÜSTERIAD)
        @Html.TextBoxFor(x => x.MÜSTERIAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.MUSTERISOYAD)
        @Html.TextBoxFor(x => x.MUSTERISOYAD, new { @class = "form-control" })
        <br />

        <button class="btn btn-primary">Müşteri Güncelle</button>


    </div>
}

MvcDbStock/Views/Musteri/YeniMüsteriEkle.cshtml
@model MvcDbStock.Models.Entity.TblMüsteri
@{
    ViewBag.Title = "YeniMüsteriEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Yeni Müsteri Ekleme Sayfası</h2>

<form method="post">
    <div>
        <label>Müşteri Ad</label>

        @Html.TextBoxFor(x => x.MÜSTERIAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.MÜSTERIAD, "", new { @style = "color:red" })
    </div>
    <div>
        <label>Müşteri Soyad</label>
        <input type="text" class="form-control" name="MUSTERISOYAD" />
        <button class="btn btn-info" id="btn1">Yeni Müşteri Ekleme</button>
    </div>
    <script>
        $('#btn1').click(function () {
            alert("Müşteri Ekleme İşlemi Yapıldı")
        })
    </script>
</form>