MvcDbStock/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcDbStock.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MvcDbStock.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        MvcDbStockEntities db = new MvcDbStockEntities();
        public ActionResult Index(int sayfa=1)
        {
        //    var value = db.TblKategori.ToList();
            var degerler = db.TblKategori.ToList().ToPagedList(sayfa, 4);
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniKategoriEkle()
        {

            return View();
        }
        [HttpPost]
        public ActionResult YeniKategoriEkle(TblKategori tblKategori)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniKategoriEkle");
            }
            db.TblKategori.Add(tblKategori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            var kategori = db.TblKategori.Find(id);
            db.TblKategori.Remove(kategori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriGetir(int id)
        {
            var ktgr = db.TblKategori.Find(id);
            return View("KategoriGetir", ktgr);
        }
        public ActionResult Guncelle(TblKategori tblKategori)
        {
            var ktgr = db.TblKategori.Find(tblKategori.KATEGORID);
            ktgr.KATEGORİAD = tblKategori.KATEGORİAD;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

MvcDbStock/Views/Kategori/Index.cshtml
@using MvcDbStock.Models.Entity;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<TblKategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Kategori Listeleme</h2>

<table class="table table-bordered">

    <tr>

        <th>Kategori ID</th>
        <th>Kategori AD</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>@item.KATEGORID</th>
            <td>@item.KATEGORİAD</td>
            <td><a href="/Kategori/Sil/@item.KATEGORID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Kategori/KategoriGetir/@item.KATEGORID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }

</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
<a href="/Kategori/YeniKategoriEkle/" class="btn btn-primary">Yeni Kategori Ekle</a>

MvcDbStock/Views/Kategori/KategoriGetir.cshtml
@model MvcDbStock.Models.Entity.TblKategori
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Kategori Getir Sayfası</h2>

@using (Html.BeginForm("Guncelle", "Kategori", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.KATEGORID)
        @Html.TextBoxFor(x => x.KATEGORID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.KATEGORİAD)
        @Html.TextBoxFor(x => x.KATEGORİAD, new { @class = "form-control" })
        <br />

        <button class="btn btn-primary">Kategori Güncelle</button>


    </div>
}

MvcDbStock/Views/Kategori/YeniKategoriEkle.cshtml
@model MvcDbStock.Models.Entity.TblKategori
@{
    ViewBag.Title = "YeniKategoriEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>YeniKategoriEkle</h2>

<form method="post">
    <div>
        
            <label>Kategori Adı</label>
            @Html.TextBoxFor(x => x.KATEGORİAD, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.KATEGORİAD, "", new { @style = "color:red" })
        </div>
        <div style="margin-top:15px">
            <button class="btn btn-info">Kategori Ekle</button>
        </div>


</form>